= Javascript Basics
Author: ashlyn

This will be a beginners javascript cookbook. I will try to organize definitions and commands in a functional way.

== Main Definitions and Examples
//::
single line comment
/* */::
multi line comment

== Variables

var::
Can be local or global.

const::
These variables cannot be redefined

NOTE: whether you define a variable locally or globally is very important with how you can call it

== Data Types
* string
* integer
* boolean
* float
* character

== Recursion
A function can be expressed in terms of itself. The function can call itself directly or indirectly resulting in a **recusive function**

.example from codecamp
function multiply(arr, n) {
  if (n <=0) {
    return 1;
  } else {
    return multiply(arr, n - 1) * arr[n-1];
  }
}

* In this example, the base case returns 1, but anything larger than n the function calls itself.

IMPORTANT: get more clarification on this topic

=== Useful functions for variables
* typeof - use to determine what type of data a variable is

NOTE: try creating a compareEquality() function using an if statement with === operator
== Strings

.Appending Variables to strings
strVarName += secStrVarName::
strings over multiple lines can be connected out of string litterals. They can be appended using +=

.Concatenating strings
strName += "text to be concatenated"::
This works the same as appending string variable names.

.String Length
variableName.string()::
Find length of string

=== Bracket Notation: Find characters of strings
Use bracket notation to specify and select a specific char. Just like how you would for strings in c

varName[0]::
number in bracket will be the letter at that position in the char count.

== escape characters
\'::
Single quote
\"::
\Double Quote
\\::
Backslash
\n::
New Line
\r::
Carriage return
\t::
Tab
\b::
Word boundary
\f::
Form feed

.String Immutability
Individual chars of strings cannot be changed, you can only change the full variable

== Math
These operations are used with strings as well.

=== Compound assignment
Assigns the value of the variable operated on by the other value to the variable.

+=::
a = a + b; === a+=b;

-=::
a = a - b; === a-=b;

*=::
a = a * b; === a*=b;

/=::
a = a / b; === a/=b;

== Arrays
Store several pieces of information in one place

.Simple arrays
var arrayName = ["strings in quotes", 3,];::
Strings in quotes, numbers are normal

.Nested or Multidimensional Arrays
[["Text", 3], ["more Text", 5]]::
Arrays can be nested like this.

.Array Indexes
arrayName[0];::
This will select the first item in the array.

* Arrays are mutable. By selecting the array index, you can change its value

.Access multidimensional arrays with Indexes
arrayName[0][1];::
This selects the 2nd item of the first array.

=== Array Manipulation

.push()
Push a parameter onto the **end** of the array

arrayName.push(1)::
This will add the number 1 to the end of the array

.pop()
take a value off the end of an array. This value can be stored and assigned to a variable. This removes the last item
* create an variable and assign it to equal the value from the other aray

var newVar = arrayName.pop();::
This will make newVar equal the last value of the array, that array will no longer contain that value.

.shift()
Just like pop but takes the first item instead of the last.

var newVar = arrayName.shift();::
Will make newVar equal the first value of the array

.unshift()
Add elements to the front of the array. Just like push but for the beginning of the array.

arrayName.unshift("Inserted information");::
This would make the string "Inserted information the content of arrayName[0]"

=== Accessing Nested Arrays
You can nest arrays and access values from nested arrays just like you would with nested objects.

.Example of a nested array
var arrayName = [
{
  variableName: "value",
                  nestedArray: [
                  "value1",
                  "value2",
                  "value3"
                  ]
}
// can put more content here
]

.How to access the nested array
arrayName[0].nestedArray[2]; // value2

== Functions
Declare a function to use again

function functionName() {function Content}::
This would create a function called functionName().

=== Returning a value from a function
Return a statement to send a value out of the function. Note that a function does not have to return a value. If return is not set to anything then the function can still be called but the return value is undefined

return "value to be returned, don't use quotes for numbers";::
When called, the function will return whatever value it's told to.

.Assignment with a returned Value
1. set a function return a value
2. assign that value to a variable as follows:

var variableName = functionName(3){}::
This code is predicated on the function taking a numeric value as an argument. It will process the number 3 and return whatever value it is told to give you relating to the input information.

.Arguments to pass values into functions
Make a function take values as arguments

function functionName(arg1){}::
arg1 would represent the input information, this can be requested from the user, be a value returned by another function...


=== Scope
Variables defined as var vs const and inside our outside fo functions will be able to be called.

Global Scope::
A variable defined globally can be seen everywhere

Local Scope::
These variables are only visible within its function

NOTE: the same name can be used for different global and local variables. It will prioritize the local variable.

== If/Else Statements and Boolean


=== Booleans
Boolean::
Use boolean expressions like little on and off switches

=== Comparison Operators
==::
An equality operator. This returns true if they're equivalent and false if they aren't. It will test across different datatypes. such as 1 == "1";

===::
strict equality operator. no type conversion, more accurate equality test.

!=::
Not operator, or unequal

!==::
Strict inequality operator

>::
Greater Than

<::
Less Than

>=::
Greater Than or Equal To

<=::
Less than or equal to

=== Logical Operators

&&::
logical and operator. if both statements are true,then the && returns true

||::
Logical or operator. if one of the statments returns true, then it is true.

=== If/Else syntax

if (condition is true) {
  execute statement
}
else return false (else notation is assumed)
 
== Switch Statements
These are used to specify values when you have multiple options to choose from.
**switch statements** test **case statements**. When the first match is made, a statemet is executed.

=== Syntax
switch(valueToBeTested) {
  case "firstValue":
  //execute code;
  break; // finishes that statement
  case "secondValue":
  //execute code;
  break; // finishes this statement
}

NOTE: You can set a default statement with the code at the end, like an else in a if/elseif else loop
default:
defaultStatement;
break;

=== Multiple switch cases with the same variables
write all the cases without breaks or arguments down, then at the end of that group write what those variables are to be equal to

== Objects
Similar to arrays but do not use an index. Data in objects are accessed through properties

* Syntax
var objectName = {
  "propertyName": "Value",
  "propertyName": "Value",
  "propertyName": ["can", "be", "an", "array"]
};

NOTE: Non-string properties will be automatically made into strings. And one word properties don't need quotes

* Objects can replace switch statements that are used like dictionaries. Their key-value relationship makes them perfect for this sort of thing. then they can be searched through effectively with syntax like **var result = objectName[variableName];**  Remember that the variableName needs to be that what you are looking for
=== Access properties
* With Dot Notation
- for when you know what the property name is
* With []
- for when the property has more than one word

* When you are accessing the value, don't use quotes. quotes are for when you want to access the variable name.

IMPORTANT: you can assign a value to a variable, then use that variable to reference objects that you already know have that value in them.

* new values can be added to properties at any time
* new properties can be added to an object at any time
* The command **delete**  can be used to delete a property at any time

=== Testing for properties
.hasOwnProperty(propertyName)::
This is useful for searching for whether or not a propertyexists. it returns a true or false

=== Accessing Properties
* link properties together down their chain when accessing different ones. ex: **objectName.property1.property2["desired values"]


== While Loop
Make something loop continuously until a condition is satisfied

.example fill an array with a countdown from 5
myArray = [];
var i = 5;
while(i >= 0) {
  myArray.push(i);
  i--;
}

== For loop
make something loop a specific number of times

.example to fill an array from 1 to 5
myArray = [];

for (var i = 1; i <=5; i++) {
  myArray.push(i);
}

NOTE: for loops can iterate in different increments. such as i +=2 to increment in 2s. They can also decrement. remember if you're going down to start with i at the high number.

=== Iterating through an array with a for loop

.example
var arrayName = [10, 9 ,8, 7, 6];
for (var i = 0; i < arr.length; i++) {
  console.log(arrayName[i]);
}

IMPORTANT: Remember that arrays are 0 indexed and that length - 1 is the last index of the array.

.Nesting For Loops
These are useful for multi-dimensional arrays. Put one loop inside the other and have their iterative variables correlate to their respective array positions. ex: arr[i][j] - the first for loop would iterate on i, the second on j

== Do while loop
This is like a while loop but it will **do** one pass of the code in the loop no matter what regarding the condition. if the while loop is true then it'll continue to do its thing.

.example
do {
  myArray.push(i);
  i++;
} while (i <5);

* it's like a while loop but with the action being placed first

== Math Functions

math.random::
returns a decimal value between 0 and 1

math.floor()::
round a number down to the nearest integer

parseInt()::
Breaks down a string and returns an integer. It takes a second argument called **radix** that specifies the base number of the string. Radix can be an integer between 2 and 36.
* Syntax: parseInt(string, radix);

.Generate a random whole number within a range
Specify a min and max number

Math.floor(Math.random*() * (max - min + 1)) + min::
This will specify a range. use static numbers of variables for the min and max points

== Ternary Operators
these can really simplify down your code

condition ? expression-if-true: expression-if-false;::
Follows a basic if/else statement

IMPORTANT: If you do multiple ternary operators at once, put them all on separate lines

.example
(condition1) ? "return statement"
: (condition2) ? "return statement"
: (condition3) ? "return statement"
